---
- name: Install Java on Redhat linux
  import_tasks: linux.yml
  when: ansible_os_family== 'RedHat'
- name: Install Java on Ubuntu OS
  import_tasks: ubuntu.yml
  when: ansible_os_family== 'Debian'